version: '3'

services:
  server:
    build:
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    networks:
      api_net:
        aliases:
          - local.docker.api
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html/symfony-fusionauth-task
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    working_dir: /var/www/html/symfony-fusionauth-task
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html/symfony-fusionauth-task
    networks:
      - api_net

  db:
    image: postgres:16.0-bookworm
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db_net
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: ${FUSIONAUTH_APP_RUNTIME_MODE}
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      FUSIONAUTH_APP_KICKSTART_FILE: ${FUSIONAUTH_APP_KICKSTART_FILE}
      FUSIONAUTH_ADMIN_PASSWORD: ${FUSIONAUTH_ADMIN_PASSWORD}
      FUSIONAUTH_API_KEY: ${FUSIONAUTH_API_KEY}
      FUSIONAUTH_APPLICATION_ID: ${FUSIONAUTH_APPLICATION_ID}
      FUSIONAUTH_TENANT_ID: ${FUSIONAUTH_TENANT_ID}
      FUSIONAUTH_USER_REGISTRATION_ID: ${FUSIONAUTH_USER_REGISTRATION_ID}
      FUSIONAUTH_ADMIN_EMAIL: ${FUSIONAUTH_ADMIN_EMAIL}
      FUSIONAUTH_WEBHOOK_URL: ${FUSIONAUTH_WEBHOOK_URL}
      FUSIONAUTH_DEFAULT_FROM_NAME: ${FUSIONAUTH_DEFAULT_FROM_NAME}
      FUSIONAUTH_DEFAULT_FROM_PORT: ${FUSIONAUTH_DEFAULT_FROM_PORT}
      FUSIONAUTH_DEFAULT_SECURITY: ${FUSIONAUTH_DEFAULT_SECURITY}
      FUSIONAUTH_DEFAULT_FROM_EMAIL: ${FUSIONAUTH_DEFAULT_FROM_EMAIL}
      FUSIONAUTH_DEFAULT_SMTP_HOST: ${FUSIONAUTH_DEFAULT_SMTP_HOST}
      FUSIONAUTH_DEFAULT_SMTP_USERNAME: ${FUSIONAUTH_DEFAULT_SMTP_USERNAME}
      FUSIONAUTH_DEFAULT_SMTP_PASSWORD: ${FUSIONAUTH_DEFAULT_SMTP_PASSWORD}

    healthcheck:
      test: curl --silent --fail http://localhost:9011/api/status -o /dev/null -w "%{http_code}"
      interval: 5s
      timeout: 5s
      retries: 5
    links:
      - server

    networks:
      - api_net
      - db_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "9011:9011"
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config
      - ./kickstart:/usr/local/fusionauth/kickstart

networks:
  api_net:
  db_net:
    driver: bridge

volumes:
  db_data:
  fusionauth_config:
